### ISSUE TITLE
Corp Partners

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#11]
Can you link logos on front page sponsor footer to company websites? Also, can you replace with the footer that you showed me breaking out the categories?

**Comment by bkeating** [comment]
A layout similar to this? 

![screen shot 2015-01-22 at 8 46 57 pm](https://cloud.githubusercontent.com/assets/157924/5869022/e6468426-a277-11e4-9c10-9f4a9342013e.png)

**Comment by vmlenz** [comment]
Yes! Even though I love the black and white footer that we have now. Can you also remove CenturyLink from the Corporate Partners list? They are not renewing :(
