### ISSUE TITLE
Subheads

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#15]
I need to add East Troy Expo and East Troy Farmers Market as subheads when scrolling over events on the homepage (i.e. Events / Santa on the Square/)

**Comment by bkeating** [comment]
Lets call the big blue menu bar the Global Menu Bar and lets call the subheads, Dropdown items.

I've just pushed an update. When you look at an Event in the admin panel, under it's settings (near bottom of page) there are two new fields: A checkbox for "display in menu" and "display_menu_title". If the checkbox is checked, the events will show up in the dropdown. If the display_menu_title field is filled in, it will display as the title for the event in the dropdown. Dropdown menu items should be no longer than a few words to keep it clean and easy to read.
