### ISSUE TITLE
Logins for current members

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#16]
I'm getting requests from members looking to login to their business profile and make adjustments, update contacts, add events, etc. Some have been trying to use old login info i.e.: (███████ and password:████) Are you able to reuse this info or is it better to create new login info?

**Comment by bkeating** [comment]
Logins work for all existing Members now. They will need to go through the password reset / 'forgot password?' process to set it however. We did *NOT* carry over their password from chamber master. It's not the most elegant thing 'go straight to the forget your password link'--we could whip up a custom page/workflow that could word it different and add some additional niceties like logging them in automatically after resetting it, etc. but that is probably overkill and not worth implementing at the moment.
