### ISSUE TITLE
News page formatting is messed up

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#17]
The formatting on the news page is messed up. Also, the link from the homepage isn't working for new stories posted.

**Comment by bkeating** [comment]
The News homepage formatting should be fixed now. There was some html code snippets in a body field that prematurely closed tags it shouldn't have. HTML tags are now stripped from the [News Homepage](http://easttroy.org/news/). 

Unclear what the broken homepage link means. All links I've checked are working(?)

**Comment by vmlenz** [comment]
Thanks for fixing! The broken home link occurs when I post something to news and then make it a homepage feature. It won't link back to the story from the home page (ie John McGivern invites you video in No. 2 top left spot)
