### ISSUE TITLE
Around the Corner Link

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#22]
Re: Around the Corner homepage banner info- Can you replace the Watch the Preview Invite Link on the homepage with a "Watch the East Troy episode" link?
Embed: 
<iframe width="560" height="315" src="https://www.youtube.com/embed/0bFe2RIH2cE" frameborder="0" allowfullscreen></iframe>

Link: https://youtu.be/0bFe2RIH2cE

**Comment by bkeating** [comment]
Updated! http://easttroy.org/
