### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by johnjamesjacoby** [ETACoC/easttroy.org#30]
How can we create pull requests if there is no code to pull?

**Comment by cgsmith** [comment]
:+1:

**Comment by bkeating** [comment]
Heck yea. I will prioritize this. Excited to have your interest.

**Comment by johnjamesjacoby** [comment]
IS THIS REAL LIFE?

**Comment by cgsmith** [comment]
OR IS THIS JUST FANTASY?

**Comment by johnjamesjacoby** [comment]
We are being .gitignored
