### ISSUE TITLE
Upcoming events sequential error

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#7]
When you click on an individual listing on the events page (i.e. Camp Edwards Howl-O-Ween Fun), the calendar of upcoming events to the right of the page is listed in the order that we entered the items. It should be listed by date of the event like it does on the main events page.

See link for example:

http://easttroy.org/events/2014/oct/24/camp-edwards-howl-o-ween-family-fun-night/

**Comment by vmlenz** [comment]
This issue is still happening.
![screen shot 2015-01-23 at 1 09 01 am](https://cloud.githubusercontent.com/assets/9220010/5871002/7eeba958-a29c-11e4-81fb-2eae5600a950.png)

**Comment by bkeating** [comment]
Weird issue with reversing the queryset to display in the calendar widget. Fixed now I believe. take a look: http://easttroy.org/events/

**Comment by vmlenz** [comment]
Hi! The calendar widget is no longer on the page now.
